import { db } from "@/db";
import { FAQ } from "@/db/schema";
import { BookMarked } from "lucide-react";
import Link from "next/link";
import { getSessionUser } from "@/lib/auth";

export const dynamic = "force-dynamic";

export default async function FAQsPage() {
  const user = await getSessionUser();
  await db();

  const faqs = await FAQ.find().sort({ category: 1, createdAt: -1 });

  const grouped = faqs.reduce((acc, faq) => {
    if (!acc[faq.category]) acc[faq.category] = [];
    acc[faq.category].push(faq);
    return acc;
  }, {} as Record<string, typeof faqs>);

  const categories = Object.keys(grouped).sort();

  return (
    <div className="flex h-screen bg-ink-950 text-cream-50 overflow-hidden font-sans">
      <div className="flex-1 flex flex-col min-w-0">
        <header className="flex h-14 shrink-0 items-center justify-between border-b border-ink-800 bg-ink-950/80 px-4 backdrop-blur sm:px-6">
          <div className="flex items-center gap-3">
            <h1 className="font-display text-lg tracking-wide text-cream-50 sm:text-xl">
              Frequently Asked Questions
            </h1>
          </div>
          <Link
            href="/"
            className="flex items-center gap-2 rounded-full bg-saffron-500/10 px-3 py-1.5 text-xs font-medium text-saffron-400 transition hover:bg-saffron-500/20"
          >
            <BookMarked className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Knowledge Studio</span>
            <span className="sm:hidden">Studio</span>
          </Link>
        </header>
        
        <main className="flex-1 overflow-y-auto p-4 sm:p-8 scroll-slim">
          <div className="mx-auto max-w-4xl space-y-12 pb-24">
            <div className="text-center mt-6 mb-12">
              <h2 className="font-display text-3xl mb-4 text-cream-50">Have questions? We have answers.</h2>
              <p className="text-ink-400 text-sm max-w-lg mx-auto">
                These FAQs are automatically generated by AI from the official documents uploaded to the Knowledge Base.
              </p>
            </div>

            {categories.length === 0 ? (
              <div className="text-center text-ink-500 mt-20">
                <p>No FAQs have been generated yet.</p>
                <p className="text-xs mt-2">Admins can upload documents to automatically generate FAQs.</p>
              </div>
            ) : (
              categories.map((category) => (
                <section key={category} className="space-y-6">
                  <h3 className="font-display text-2xl text-saffron-400 border-b border-ink-800 pb-2">{category}</h3>
                  <div className="grid gap-4 sm:grid-cols-2">
                    {grouped[category].map((faq: any) => (
                      <div key={faq._id.toString()} className="rounded-2xl border border-ink-800 bg-ink-900/50 p-5 hover:border-ink-700 transition">
                        <h4 className="font-medium text-cream-100 mb-2 leading-snug">{faq.question}</h4>
                        <p className="text-sm text-ink-300 leading-relaxed">{faq.answer}</p>
                      </div>
                    ))}
                  </div>
                </section>
              ))
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
